name = "release-watch"
main = "src/worker.js"
compatibility_date = "2023-10-30"

# Cron Trigger: Run every hour
[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "release-watch-db"
database_id = "f7ebd7c8-8954-42c8-a65d-142c5c8c6788"

# Environment variables (secrets should be set via `wrangler secret put`)
# [vars]
# BARK_KEY = "..."
# GH_TOKEN = "..."
